- cncnet-api/package-lock.json
Reverts CnCNet/cncnet-ladder-api#31
Accidental commit on the wrong project, apologies.
> Revert "Bump y18n from 3.2.1 to 3.2.2 in /cncnet-api"

- cncnet-api/app/Console/Commands/GenerateBulkRecords.php
- cncnet-api/app/Http/Controllers/MapPoolController.php
- Update reorderMapPool function to accept 2nd parameter of ladderId
- Update generate bulk records with pagination
> fix map ordering bug, update bulk generate records with pagination

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
Check for the player's actual side, not their chosen side.
> check for actual side, not chosen side

- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/resources/views/admin/manage-users.blade.php
- Add option to search by exact username
- fix 'clear search' button
- lower pagination 20 results
> add option for exact user search

- cncnet-api/app/Http/Controllers/LadderController.php
Create new ladders starting from current year.
> add ladders starting from current year

- cncnet-api/app/PlayerActiveHandle.php
When checking if active player has played any games this month, check their games played from game model not player game report
> Active player  games played check

- cncnet-api/app/Http/Controllers/ApiUserController.php
- cncnet-api/app/Http/Controllers/v2/ApiUserController.php
- cncnet-api/app/Http/routes.php
- cncnet-api/app/Ladder.php
- cncnet-api/app/User.php
- Will show private ladders in the QM client if they are an admin, a ladder admin or ladder tester.
> Allow ladders to show up in qm client for testers

- cncnet-api/app/Http/Controllers/AccountController.php
- cncnet-api/app/Http/Controllers/ApiLadderController.php
- cncnet-api/app/Http/Controllers/ApiUserController.php
- cncnet-api/app/Http/Controllers/LadderController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Http/Services/PlayerService.php
- cncnet-api/app/Http/routes.php
- cncnet-api/app/Ladder.php
- cncnet-api/app/PlayerActiveHandle.php
- cncnet-api/app/Providers/Navigation.php
- cncnet-api/resources/views/auth/account.blade.php
- cncnet-api/resources/views/components/navigation.blade.php
> WIP - auto register temp nicks

- cncnet-api/app/Http/Controllers/ApiLadderController.php
- cncnet-api/app/Http/Controllers/ApiUserController.php
- cncnet-api/app/Http/Controllers/Auth/AuthController.php
- cncnet-api/app/Http/Controllers/LadderController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Ladder.php
- cncnet-api/app/Stats.php
- cncnet-api/app/Stats2.php
- cncnet-api/database/migrations/2022_09_11_003908_createAchievementTableTracker.php
- cncnet-api/database/migrations/2022_11_01_220002_AchievementsProgressNew.php
- Only create achievement progress when user has made progress towards the achievement
> refactor achievements

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/LadderService.php
- only display players' names in active games if duration is more than 2 mins
- display players factions
- display duration of game
> enhance api

- cncnet-api/app/Http/Controllers/AccountController.php
Resolve https://github.com/CnCNet/cncnet-ladder-api/issues/142
> Animated avatars

- cncnet-api/app/Http/Controllers/MapPoolController.php
- cncnet-api/database/migrations/2022_12_29_173107_TrimMapNames.php
- Migration to trim map names
- Trim map names going forward
> trim whitespace from map names

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/routes.php
- cncnet-api/resources/views/ladders/games-listing.blade.php
Discord bot will call this API to fetch errored games
> add route to fetch errored games

- cncnet-api/app/GameAudit.php
- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/app/Http/Controllers/MapPoolController.php
- cncnet-api/app/Http/routes.php
- cncnet-api/database/migrations/2022_12_31_155928_GameAudit.php
- cncnet-api/resources/views/admin/index.blade.php
- cncnet-api/resources/views/admin/washed-games.blade.php
- Create admin page "Washed Games", view games that have been washed
> log washed games

- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/app/Http/Controllers/ApiLadderController.php
- cncnet-api/app/Http/routes.php
- cncnet-api/resources/views/ladders/_modal-edit-player-name.blade.php
- cncnet-api/resources/views/ladders/player-detail.blade.php
> allow ladder mods to update player nickname

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Http/routes.php
- Fetch stats filtered on ladder tier
- Fetch current matches filtered on ladder tier
> stats based on tier

- cncnet-api/app/Http/Controllers/ApiLadderController.php
- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- fix query
- temporarily log stats for 1 user, for debugging
> fix achievements?

- cncnet-api/app/Http/Controllers/AccountController.php
- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/AdminService.php
- cncnet-api/app/QmLadderRules.php
- cncnet-api/app/User.php
- cncnet-api/app/UserSettings.php
- cncnet-api/database/migrations/2023_04_10_140138_add_match_ai_to_user_settings_table.php
- cncnet-api/database/migrations/2023_04_10_143015_add_match_ai_seconds_column_to_qm_ladder_rules.php
- cncnet-api/resources/views/admin/ladder-setup.blade.php
- cncnet-api/resources/views/auth/account-settings.blade.php
Also added is the ability to configure the amount of seconds until AI matching is allowed in ladder settings.
> AI bot matching preference in user settings

- cncnet-api/app/Commands/Matchup/BaseMatchupHandler.php
- cncnet-api/app/Commands/Matchup/PlayerMatchupHandler.php
- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/app/Http/Services/QuickMatchService.php
- cncnet-api/app/Http/Services/UserRatingService.php
- cncnet-api/app/Http/routes.php
- cncnet-api/app/LeaguePlayer.php
- cncnet-api/app/User.php
- cncnet-api/app/UserTier.php
- cncnet-api/database/migrations/2023_07_30_142448_user_tiers_table.php
- cncnet-api/resources/views/admin/players/ratings.blade.php
Simple checks for if a user is tier 1 or 2 for each ladder
> Removes LeaguePlayer model, UserTier model added

- cncnet-api/app/Http/Controllers/MapPoolController.php
- cncnet-api/app/Http/Services/QuickMatchService.php
- cncnet-api/database/migrations/2023_09_05_233802_AddQmMapWeight.php
- cncnet-api/resources/views/admin/edit-map-pool.blade.php
- add ability to set the 'weight' on a qm map.  Defaults to 1. Increased weight = increased odds of being picked
> add map weight

- cncnet-api/app/Http/Controllers/ApiPlayerController.php
- cncnet-api/app/Http/Services/StatsService.php
- cncnet-api/app/Http/routes.php
- cncnet-api/app/PlayerActiveHandle.php
Qm client endpoints for create username, toggle status and get all usernames
> Qm client endpoints for create username, toggle status

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Models/Ladder.php
- cncnet-api/app/Models/LadderHistory.php
> optimize api stats all

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Models/Ladder.php
> optimize endpoint /api/v1/qm/ladder/{ladderAbbrev}/current_matches

- cncnet-api/app/Http/Controllers/Admin/PodiumController.php
- cncnet-api/app/Http/Requests/Admi/Podium/ComputePodiumRequest.php
- cncnet-api/resources/views/admin/index.blade.php
- cncnet-api/resources/views/admin/podium.blade.php
- cncnet-api/resources/views/admin/podium/result-too-many-attempts.blade.php
- cncnet-api/resources/views/admin/podium/result.blade.php
- cncnet-api/routes/web.php
Form : 
Result :
Form validation okay
Only available to mod/admin
> Podium - Page to get top 3 players with most win for a period on a ladder.

- cncnet-api/app/Providers/Navigation.php
- cncnet-api/resources/views/components/navigation/fullscreen-menu.blade.php
- cncnet-api/resources/views/components/navigation/ladders.blade.php
> Add ladder link to mobile menu

- cncnet-api/database/migrations/2024_05_19_020260_trim_yr_maps.php
- cncnet-api/database/migrations/2024_05_27_213534_r_a22v2.php
- cncnet-api/routes/api.php
- dev_setup.sh
> Routing method get active

- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/resources/views/admin/manage-users.blade.php
Adds search for user by id or alias. Helpful when looking for duplicates or searching for a player who never used his alias as a player name.
> Added search by alias or user id.

- cncnet-api/app/Http/Controllers/ApiLadderController.php
- cncnet-api/app/Http/Services/LadderService.php
Referring to https://discord.com/channels/1089195585984286860/1089944165632180296/1383644832903462945
> Changed parameter order.

- cncnet-api/app/Http/Controllers/ApiQuickMatchController.php
- cncnet-api/app/Http/Services/LadderService.php
- cncnet-api/app/Http/Services/StatsService.php
> refine stats endpoint

- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/resources/views/admin/_duplicates.blade.php
- cncnet-api/resources/views/admin/_nicknames.blade.php
- cncnet-api/resources/views/admin/manage-users.blade.php
- Move all DB calls to controller, remove all DB calls from view
- On UI, show 10 IP's, with a button to show more. (Previously all IP's were being loaded and there could be hundreds)
- Limit results to up to 10 users, more than that should not be necessary, narrow your search input
- Implement eager loading in queries
> optimize ManageUsers endpoint

- cncnet-api/app/Http/Controllers/AdminController.php
- cncnet-api/app/Http/Controllers/Api/V2/Qm/MatchUpController.php
- cncnet-api/app/Http/Services/QuickMatchService.php
- cncnet-api/app/Http/Services/QuickMatchSpawnService.php
- cncnet-api/app/Http/Services/TwitchService.php
- cncnet-api/config/services.php
With this PR, the code will verify that an observer is live streaming on twitch. If the user is not streaming on twitch, they will not be able to observer quick matches.
> verify observer is streaming on twitch
